export function initMeshScaleCalibration({ input, mount }) {
  let files = [], meta = null, initialScale = 0.2, scale = 0.2, objectUrls = [], views = [], dragging = -1;
  const q = s => mount.querySelector(s);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const base=p=>String(p||'').replace(/\\/g,'/').split('/').pop();
  mount.innerHTML = `<section class="cal"><div class="cal-head"><b>Multiview input & mesh scale</b><span id="cal-badge">select files</span></div><div id="cal-drop" class="cal-drop" tabindex="0">Drop RGBA views + transforms.json here<br><small>or click to choose files</small></div><div id="cal-summary" class="cal-msg"></div><div id="cal-grid" class="cal-grid"></div><div class="cal-msg">Drag cards to reorder. The patched transforms.json uses the same frame order.</div><div class="cal-controls"><input id="cal-range" type="range" min="0.02" max="2" step="0.001" value="0.2"><input id="cal-num" type="number" min="0.001" max="4" step="0.001" value="0.200"></div><div id="cal-msg" class="cal-msg">Blue guides are linked across views.</div><button id="cal-save">Download patched transforms.json</button></section>`;
  const range=q('#cal-range'), num=q('#cal-num'), grid=q('#cal-grid'), badge=q('#cal-badge'), msg=q('#cal-msg'), drop=q('#cal-drop'), summary=q('#cal-summary');
  function cleanup(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];views=[];}
  function orderedMeta(){return {...meta,mesh_scale:scale,frames:views.map(v=>v.frame)};}
  function renderCards(){grid.innerHTML='';views.slice(0,8).forEach((v,i)=>{const c=document.createElement('div');c.className='cal-view';c.draggable=true;c.dataset.index=String(i);c.innerHTML=`<img><div class="guide"></div><span></span><b class="ord">${i+1}</b>`;c.querySelector('img').src=v.url;c.querySelector('span').textContent=v.frame.file_path;c.ondragstart=()=>{dragging=i;c.classList.add('dragging');};c.ondragend=()=>{dragging=-1;c.classList.remove('dragging');};c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();const t=+c.dataset.index;if(dragging<0||t===dragging)return;const [m]=views.splice(dragging,1);views.splice(t,0,m);dragging=-1;renderCards();updateGuide();};grid.appendChild(c);});}
  function updateGuide(){scale=clamp(+num.value||initialScale,0.001,4);num.value=scale.toFixed(3);range.value=String(clamp(scale,0.02,2));const ratio=clamp(initialScale/scale,.22,2.2);grid.querySelectorAll('.guide').forEach(g=>{g.style.width=`${clamp(72*ratio,18,96)}%`;g.style.height=`${clamp(72*ratio,18,96)}%`;});badge.textContent=`mesh_scale ${scale.toFixed(3)}`;badge.className=scale<.02||scale>2?'warn':'ok';}
  range.oninput=()=>{num.value=(+range.value).toFixed(3);updateGuide();};num.oninput=updateGuide;
  async function ingest(list){cleanup();files=[...list];const tf=files.find(f=>f.name==='transforms.json'||f.name.toLowerCase().endsWith('.json'));if(!tf){meta=null;grid.innerHTML='';badge.textContent='transforms.json missing';badge.className='warn';summary.textContent=`${files.length} file(s)`;return;}try{meta=JSON.parse(await tf.text());}catch{meta=null;badge.textContent='invalid transforms.json';badge.className='warn';return;}if(!Array.isArray(meta.frames)||!meta.frames.length){meta=null;badge.textContent='no frames in transforms.json';badge.className='warn';return;}initialScale=Number.isFinite(meta.mesh_scale)&&meta.mesh_scale>0?meta.mesh_scale:.2;scale=initialScale;num.value=scale.toFixed(3);range.value=String(clamp(scale,.02,2));const by=new Map();files.filter(f=>f.type.startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(f.name)).forEach(f=>{by.set(f.name,f);const rel=f.webkitRelativePath?.split('/').slice(1).join('/');if(rel)by.set(rel,f);});for(const fr of meta.frames){const key=String(fr.file_path||'').replace(/^\.\//,'');const f=by.get(fr.file_path)||by.get(key)||by.get(base(key));if(!f)continue;const url=URL.createObjectURL(f);objectUrls.push(url);views.push({file:f,frame:fr,url});}summary.textContent=`${views.length}/${meta.frames.length} views matched`;msg.textContent=views.length?`Loaded ${views.length} views. Adjust mesh_scale if needed, then run.`:'No images matched frames[].file_path';renderCards();updateGuide();}
  input.addEventListener('change',()=>ingest([...input.files]));
  drop.onclick=()=>input.click();drop.onkeydown=e=>{if(e.key==='Enter')input.click();};['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag');}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag');}));drop.addEventListener('drop',e=>ingest([...e.dataTransfer.files]));
  q('#cal-save').onclick=()=>{if(!meta)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(orderedMeta(),null,2)],{type:'application/json'}));a.download='transforms.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  return { getPatchedFiles(){if(!meta)return files;const patched=new File([JSON.stringify(orderedMeta(),null,2)],'transforms.json',{type:'application/json'});const imgs=views.map(v=>v.file);return [patched,...imgs];}, getScale(){return scale;}, getViewCount(){return views.length;}, isReady(){return !!meta&&views.length>0;} };
}
