#!/usr/bin/env python3
"""issue #61 用の独立 fixture 生成器。

`tools/ref_trellis2_mv_inject.py`（#59 でピン留めした逐語ベンダリング）を実際に実行し、
native `sample_flow_multi`（issue #61）が再現すべき **実数値**（CFG/guidance_rescale を
経た最終 sample・per-step 予測値）をテキストへダンプする。

この生成物は C++ 実装の数式を一切参照しない（pin 済み Python コードを動かした出力を
そのまま書き出すだけ）。したがって C++ 側の実装ミスとこの fixture の期待値が同じ転記ミスを
共有するリスクが構造的に無い（設計ドキュメント 4.2 節、codex レビュー 2026-09-21 P0 対応）。

出力形式はプレーンテキスト（本リポジトリに汎用 JSON パーサが無いため）。1 ケース = 1 ブロック。
このリポジトリに一般的な JSON ライブラリが無いのは意図的な既存方針
（`include/transforms_json.h` も専用の手書きパーサ）なので、それに倣う。

実行:
    .venv/bin/python tools/gen_trellis2_mv_sampler_fixture.py > tests/fixtures/trellis2_mv_sampler/sampler_oracle.txt
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ref_trellis2_mv_inject import (
    FlowEulerGuidanceIntervalSampler,
    inject_sampler_multi_image,
)

DIM = 6


def make_cond(num_views: int) -> torch.Tensor:
    return torch.tensor([[(v + 1) * 10.0] for v in range(num_views)], dtype=torch.float32)


def make_neg_cond() -> torch.Tensor:
    return torch.zeros((1, 1), dtype=torch.float32)


def decode_tag(cond_row: torch.Tensor):
    val = float(cond_row.flatten()[0].item())
    if abs(val) < 1e-9:
        return None
    return int(round(val / 10.0)) - 1


def make_fake_model(log: list, dim: int = DIM):
    def model(x_t, t_tensor, cond, **kwargs):
        t_val = float(t_tensor[0].item()) / 1000.0
        view = decode_tag(cond)
        log.append({"view": view, "t": t_val})
        if view is None:
            scale, offset = 0.2, 0.0
        else:
            scale, offset = 1.0 + 0.4 * view, 0.5 * (view + 1)
        base = torch.tensor([math.sin(3.0 * t_val + k) for k in range(dim)], dtype=x_t.dtype)
        return (offset + scale * base).unsqueeze(0)
    return model


def fmt_vec(t: torch.Tensor) -> str:
    return " ".join(f"{v:.9g}" for v in t.flatten().tolist())


def emit_tseq(name: str, steps: int, rescale_t: float):
    """t-schedule のみを独立にダンプする（flow_euler.py:238-239 と一字一句同じ2行 -- 再実装で
    なく参照コードそのものの実行結果なので、C++側 flow_t_schedule() との突き合わせに転記ミス
    共有リスクが無い）。fixture 名の末尾 `_production` は #59 docs/spec/33 の実パラメータ表
    （SS/shape/texture の3ステージ）に対応する。%.17g は double を bit 単位で往復させるのに
    十分な精度（IEEE754 double は最大 17 桁で一意に表現可能）。
    """
    t_seq = np.linspace(1, 0, steps + 1)
    t_seq = rescale_t * t_seq / (1 + (rescale_t - 1) * t_seq)
    print(f"TSEQ {name}")
    print(f"TSEQ_STEPS {steps}")
    print(f"TSEQ_RESCALE_T {rescale_t:.17g}")
    print("TSEQ_VALUES " + " ".join(f"{v:.17g}" for v in t_seq.tolist()))
    print("END")
    print()


def run_case(mode: str, V: int, steps: int, rescale_t: float, gi0: float, gi1: float,
             guidance_strength: float, guidance_rescale: float, dim: int = DIM):
    sampler = FlowEulerGuidanceIntervalSampler(sigma_min=1e-5)
    cond, neg_cond = make_cond(V), make_neg_cond()
    noise = torch.zeros((1, dim))
    log: list = []
    model = make_fake_model(log, dim)
    with inject_sampler_multi_image(sampler, V, steps, mode=mode):
        out = sampler.sample(
            model, noise, cond=cond, neg_cond=neg_cond, steps=steps, rescale_t=rescale_t,
            guidance_strength=guidance_strength, guidance_interval=(gi0, gi1),
            guidance_rescale=guidance_rescale, verbose=False,
        )
    return log, out.samples


def emit_case(name: str, mode: str, V: int, steps: int, rescale_t: float, gi0: float, gi1: float,
              guidance_strength: float, guidance_rescale: float, dim: int = DIM):
    log, final_sample = run_case(mode, V, steps, rescale_t, gi0, gi1, guidance_strength,
                                  guidance_rescale, dim)
    print(f"CASE {name}")
    print(f"MODE {mode}")
    print(f"V {V}")
    print(f"STEPS {steps}")
    print(f"DIM {dim}")
    print(f"RESCALE_T {rescale_t:.9g}")
    print(f"GI0 {gi0:.9g}")
    print(f"GI1 {gi1:.9g}")
    print(f"GUIDANCE_STRENGTH {guidance_strength:.9g}")
    print(f"GUIDANCE_RESCALE {guidance_rescale:.9g}")
    print(f"NCALLS {len(log)}")
    for e in log:
        view = e["view"] if e["view"] is not None else -1
        print(f"CALL {view} {e['t']:.9g}")
    print(f"FINAL {fmt_vec(final_sample)}")
    print("END")
    print()


def main():
    torch.manual_seed(0)
    print("# auto-generated by tools/gen_trellis2_mv_sampler_fixture.py -- issue #61 独立 fixture")
    print("# 生成元: tools/ref_trellis2_mv_inject.py (#59 でピン留めした逐語ベンダリング)")
    print("# 再生成: .venv/bin/python tools/gen_trellis2_mv_sampler_fixture.py")
    print()

    # Case E: multidiffusion, 区間内, rescale有
    emit_case("md_interval_rescale", "multidiffusion", V=3, steps=6, rescale_t=2.0,
              gi0=0.3, gi1=0.8, guidance_strength=2.0, guidance_rescale=0.4)

    # Case F: multidiffusion, guidance_strength=1.0 (短絡が起きないことの数値的裏取り), rescale有
    emit_case("md_strength1_no_shortcircuit", "multidiffusion", V=2, steps=6, rescale_t=1.5,
              gi0=0.3, gi1=0.6, guidance_strength=1.0, guidance_rescale=0.3)

    # Case G: multidiffusion, guidance_strength低め(0.3), rescale有。
    # 注: guidance_strength=0.0 だとこの fake model では std_pos/std_cfg 比が 6.0 に達し、
    # native実装が既存 sample_flow から継承している OOD保護クランプ [0.2,5.0]
    # （参照アルゴリズムには無い native 側の頑健性追加、docs/design/...-sampler-fusion.md §6）
    # に触れてしまう。このfixtureは「rescaleの数式順序」を検証する独立oracleであって
    # クランプの挙動を検証する場ではないため、ratio が自然に範囲内に収まる guidance_strength=0.3
    # を使う（短絡が起きないこと自体は 4.1-7 の構造的テストで別途 guidance_strength=0 を検証済み）。
    emit_case("md_strength_low_rescale", "multidiffusion", V=2, steps=4, rescale_t=1.0,
              gi0=0.0, gi1=1.0, guidance_strength=0.3, guidance_rescale=0.5)

    # TSEQ: 本番3ステージのt-schedule生の値（統括の検証差し戻し 2026-09-21 対応 -- t-schedule
    # を float32 で計算していた既存 sample_flow のバグが shape_slat_sampler の本番パラメータで
    # 境界(t==0.6)の分類を誤らせていた。C++側 flow_t_schedule() の出力をこの生の double 列と
    # bit-exact 比較することで、境界分類だけでなくschedule自体の再現度も検証する）。
    # docs/spec/33-trellis2-mv-reference.md の実パラメータ表より。
    emit_tseq("sparse_structure_sampler_production", steps=12, rescale_t=5.0)
    emit_tseq("shape_slat_sampler_production", steps=12, rescale_t=3.0)
    emit_tseq("tex_slat_sampler_production", steps=12, rescale_t=3.0)

    # Case I: shape_slat_sampler の本番パラメータ（steps/rescale_t/guidance_interval/
    # guidance_strengthは実パラメータ表と同一値）で境界ケース (t==0.6 ちょうど) を独立 fixture
    # として固定する。将来のリファクタでこの境界が再び float32 相当に劣化して inside から
    # 漏れても、この fixture が正しい呼び出し回数（NCALLS: 全V*steps回のpositive +
    # inside step数回のnegative）で検出する
    # （ユーザー指示 (3): 「shape の本番パラメータ境界ケースを独立の fixture として追加」）。
    # guidance_rescale は本番の0.5でなく0.0にする: このfixtureの目的はschedule/interval境界の
    # 回帰検出であって guidance_rescale 数式の裏取り（それは Case E/F/G が別途担う）ではなく、
    # guidance_strength=7.5（本番値）と組み合わせると native 側の OOD保護クランプ[0.2,5.0]
    # （参照アルゴリズムに無い native 側の頑健性追加、docs/design/...-sampler-fusion.md §6）に
    # 触れて実測比が変わり、Python の unclamped rescale と native の clamped rescale が数値的に
    # 乖離してしまう（Case G と同じ理由、tools/gen_trellis2_mv_sampler_fixture.py 上のコメント参照）。
    emit_case("shape_production_boundary", "multidiffusion", V=2, steps=12, rescale_t=3.0,
              gi0=0.6, gi1=1.0, guidance_strength=7.5, guidance_rescale=0.0)

    # Case H: stochastic cascade -- LR run, counter-continued HR run, counter-reset HR run
    V, steps, rescale_t, gi0, gi1 = 3, 5, 1.3, 0.0, 1.0
    guidance_strength, guidance_rescale = 1.7, 0.3
    sampler = FlowEulerGuidanceIntervalSampler(sigma_min=1e-5)
    cond, neg_cond = make_cond(V), make_neg_cond()
    lr_log: list = []
    hr_log: list = []
    with inject_sampler_multi_image(sampler, V, steps, mode="stochastic"):
        lr_out = sampler.sample(
            make_fake_model(lr_log), torch.zeros((1, DIM)), cond=cond, neg_cond=neg_cond,
            steps=steps, rescale_t=rescale_t, guidance_strength=guidance_strength,
            guidance_interval=(gi0, gi1), guidance_rescale=guidance_rescale, verbose=False,
        ).samples
        hr_out_continued = sampler.sample(
            make_fake_model(hr_log), torch.zeros((1, DIM)), cond=cond, neg_cond=neg_cond,
            steps=steps, rescale_t=rescale_t, guidance_strength=guidance_strength,
            guidance_interval=(gi0, gi1), guidance_rescale=guidance_rescale, verbose=False,
        ).samples

    reset_log: list = []
    sampler2 = FlowEulerGuidanceIntervalSampler(sigma_min=1e-5)
    with inject_sampler_multi_image(sampler2, V, steps, mode="stochastic"):
        hr_out_reset = sampler2.sample(
            make_fake_model(reset_log), torch.zeros((1, DIM)), cond=cond, neg_cond=neg_cond,
            steps=steps, rescale_t=rescale_t, guidance_strength=guidance_strength,
            guidance_interval=(gi0, gi1), guidance_rescale=guidance_rescale, verbose=False,
        ).samples

    print("CASE stochastic_cascade")
    print("MODE stochastic")
    print(f"V {V}")
    print(f"STEPS {steps}")
    print(f"DIM {DIM}")
    print(f"RESCALE_T {rescale_t:.9g}")
    print(f"GI0 {gi0:.9g}")
    print(f"GI1 {gi1:.9g}")
    print(f"GUIDANCE_STRENGTH {guidance_strength:.9g}")
    print(f"GUIDANCE_RESCALE {guidance_rescale:.9g}")
    print(f"LR_NCALLS {len(lr_log)}")
    for e in lr_log:
        view = e["view"] if e["view"] is not None else -1
        print(f"LR_CALL {view} {e['t']:.9g}")
    print(f"LR_FINAL {fmt_vec(lr_out)}")
    print(f"HR_CONTINUED_NCALLS {len(hr_log)}")
    for e in hr_log:
        view = e["view"] if e["view"] is not None else -1
        print(f"HR_CONTINUED_CALL {view} {e['t']:.9g}")
    print(f"HR_CONTINUED_FINAL {fmt_vec(hr_out_continued)}")
    print(f"HR_RESET_NCALLS {len(reset_log)}")
    for e in reset_log:
        view = e["view"] if e["view"] is not None else -1
        print(f"HR_RESET_CALL {view} {e['t']:.9g}")
    print(f"HR_RESET_FINAL {fmt_vec(hr_out_reset)}")
    assert not torch.equal(hr_out_continued, hr_out_reset), \
        "cascade fixture is degenerate: continued and reset HR runs must differ"
    print("END")


if __name__ == "__main__":
    main()
